### ISSUE TITLE
Testar a tela de login de forma exploratória.

### ISSUE THREAD

**Issue by wab030** [viniciuscrw/cestas-cooperflora-rn#12]
Yasmin gostaria que você testasse a tela de login do app. Pode brincar a vontade e tentar encontrar erros. Se encontrar abra os erros no GitHub. Dúvidas fale comigo.

**Comment by mimi124515** [comment]
Link para tabela de testes: (https://docs.google.com/spreadsheets/d/1IEbrixfTt-F_fQ0mKChQBFMsfVQs8E0HTe-OsrKCLlc/edit)
